
name: Continuous Integration

on:
  push:
    branches: [ master, develop, test ]
  pull_request:
    branches: [ master, develop, test ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run tests
        run: npm run test
